import firebase from "./firebase.js";
var link = document.getElementById("show");
link.addEventListener("click", infoReturn);
function infoReturn() {
  firebase.auth().onAuthStateChanged(function (user) {
    if (user) {
      // User is signed in.
      // ...
      return;
    } else {
      // User is signed out.
      // ...
      window.location.href = "login.html";
    }
  });

  var obj = {
    patient: [
      {
        first_name: "Cosme",
        last_name: "Battell",
        gender: "Male",
        temperature: 35.9,
        pulse_rate: 126,
        oxygen_level: 92,
        bp: 140,
        nasal_airflow: 11,
        sc: 11.1,
        A1C: 6.7,
        gl: 88.7,
      },
      {
        first_name: "Lena",
        last_name: "Hallick",
        gender: "Female",
        temperature: 32.7,
        pulse_rate: 124,
        oxygen_level: 97,
        bp: 115,
        nasal_airflow: 20,
        sc: 2.8,
        A1C: 8.0,
        gl: 84.9,
      },
      {
        first_name: "Lacey",
        last_name: "Busfield",
        gender: "Female",
        temperature: 32.9,
        pulse_rate: 115,
        oxygen_level: 100,
        bp: 119,
        nasal_airflow: 19,
        sc: 1.2,
        A1C: 5.5,
        gl: 79.4,
      },
      {
        first_name: "Dall",
        last_name: "Freed",
        gender: "Male",
        temperature: 30.7,
        pulse_rate: 93,
        oxygen_level: 98,
        bp: 143,
        nasal_airflow: 16,
        sc: 6.5,
        A1C: 13.7,
        gl: 118.2,
      },
      {
        first_name: "Kaitlyn",
        last_name: "Giraudeau",
        gender: "Female",
        temperature: 33.5,
        pulse_rate: 68,
        oxygen_level: 94,
        bp: 117,
        nasal_airflow: 28,
        sc: 18.7,
        A1C: 11.8,
        gl: 57.4,
      },
      {
        first_name: "Cameron",
        last_name: "Guillotin",
        gender: "Male",
        temperature: 36.4,
        pulse_rate: 128,
        oxygen_level: 100,
        bp: 107,
        nasal_airflow: 32,
        sc: 18.1,
        A1C: 8.7,
        gl: 56.6,
      },
      {
        first_name: "Perry",
        last_name: "Santos",
        gender: "Female",
        temperature: 34.7,
        pulse_rate: 64,
        oxygen_level: 99,
        bp: 150,
        nasal_airflow: 20,
        sc: 15.4,
        A1C: 7.6,
        gl: 102.0,
      },
      {
        first_name: "Pepito",
        last_name: "Janway",
        gender: "Male",
        temperature: 39.2,
        pulse_rate: 82,
        oxygen_level: 96,
        bp: 121,
        nasal_airflow: 31,
        sc: 3.8,
        A1C: 7.5,
        gl: 102.7,
      },
      {
        first_name: "Bryon",
        last_name: "Spoor",
        gender: "Male",
        temperature: 35.4,
        pulse_rate: 123,
        oxygen_level: 94,
        bp: 126,
        nasal_airflow: 18,
        sc: 3.2,
        A1C: 6.3,
        gl: 87.2,
      },
      {
        first_name: "Manya",
        last_name: "Witheridge",
        gender: "Female",
        temperature: 38.1,
        pulse_rate: 77,
        oxygen_level: 99,
        bp: 96,
        nasal_airflow: 30,
        sc: 1.6,
        A1C: 8.7,
        gl: 46.4,
      },
      {
        first_name: "Dore",
        last_name: "Imort",
        gender: "Male",
        temperature: 30.1,
        pulse_rate: 118,
        oxygen_level: 94,
        bp: 114,
        nasal_airflow: 40,
        sc: 10.2,
        A1C: 5.4,
        gl: 45.5,
      },
      {
        first_name: "Jeramie",
        last_name: "Sandall",
        gender: "Male",
        temperature: 34.6,
        pulse_rate: 63,
        oxygen_level: 92,
        bp: 141,
        nasal_airflow: 10,
        sc: 5.7,
        A1C: 7.5,
        gl: 94.0,
      },
      {
        first_name: "Sasha",
        last_name: "Radage",
        gender: "Male",
        temperature: 31.8,
        pulse_rate: 126,
        oxygen_level: 90,
        bp: 142,
        nasal_airflow: 13,
        sc: 13.1,
        A1C: 3.5,
        gl: 76.1,
      },
      {
        first_name: "Chrissy",
        last_name: "Trenam",
        gender: "Male",
        temperature: 31.5,
        pulse_rate: 71,
        oxygen_level: 90,
        bp: 114,
        nasal_airflow: 40,
        sc: 9.7,
        A1C: 14.7,
        gl: 81.6,
      },
      {
        first_name: "Bondy",
        last_name: "Awton",
        gender: "Male",
        temperature: 31.9,
        pulse_rate: 80,
        oxygen_level: 94,
        bp: 107,
        nasal_airflow: 27,
        sc: 1.4,
        A1C: 13.7,
        gl: 92.8,
      },
      {
        first_name: "Dawn",
        last_name: "Jelf",
        gender: "Female",
        temperature: 33.7,
        pulse_rate: 80,
        oxygen_level: 90,
        bp: 105,
        nasal_airflow: 17,
        sc: 1.7,
        A1C: 12.2,
        gl: 117.5,
      },
      {
        first_name: "Cathyleen",
        last_name: "Brewer",
        gender: "Female",
        temperature: 32.2,
        pulse_rate: 130,
        oxygen_level: 91,
        bp: 118,
        nasal_airflow: 40,
        sc: 13.4,
        A1C: 14.5,
        gl: 107.8,
      },
      {
        first_name: "Aimee",
        last_name: "Schober",
        gender: "Female",
        temperature: 34.9,
        pulse_rate: 58,
        oxygen_level: 95,
        bp: 104,
        nasal_airflow: 6,
        sc: 15.3,
        A1C: 9.3,
        gl: 120.1,
      },
      {
        first_name: "Othilia",
        last_name: "Perillio",
        gender: "Female",
        temperature: 37.0,
        pulse_rate: 91,
        oxygen_level: 94,
        bp: 135,
        nasal_airflow: 30,
        sc: 19.3,
        A1C: 3.6,
        gl: 100.4,
      },
      {
        first_name: "Dorthea",
        last_name: "Kolodziejski",
        gender: "Female",
        temperature: 33.3,
        pulse_rate: 89,
        oxygen_level: 95,
        bp: 129,
        nasal_airflow: 27,
        sc: 18.6,
        A1C: 4.4,
        gl: 78.6,
      },
      {
        first_name: "Florri",
        last_name: "Okenfold",
        gender: "Female",
        temperature: 33.9,
        pulse_rate: 78,
        oxygen_level: 90,
        bp: 140,
        nasal_airflow: 39,
        sc: 3.7,
        A1C: 4.2,
        gl: 103.4,
      },
      {
        first_name: "Cayla",
        last_name: "McVanamy",
        gender: "Female",
        temperature: 34.1,
        pulse_rate: 107,
        oxygen_level: 92,
        bp: 131,
        nasal_airflow: 16,
        sc: 16.4,
        A1C: 6.6,
        gl: 63.3,
      },
      {
        first_name: "Desirae",
        last_name: "Ricson",
        gender: "Female",
        temperature: 40.0,
        pulse_rate: 73,
        oxygen_level: 92,
        bp: 102,
        nasal_airflow: 28,
        sc: 11.9,
        A1C: 4.6,
        gl: 58.0,
      },
      {
        first_name: "Tobey",
        last_name: "Clayfield",
        gender: "Female",
        temperature: 32.9,
        pulse_rate: 104,
        oxygen_level: 98,
        bp: 92,
        nasal_airflow: 18,
        sc: 12.2,
        A1C: 6.2,
        gl: 99.8,
      },
      {
        first_name: "Estelle",
        last_name: "Janik",
        gender: "Female",
        temperature: 37.1,
        pulse_rate: 84,
        oxygen_level: 94,
        bp: 132,
        nasal_airflow: 13,
        sc: 16.1,
        A1C: 10.9,
        gl: 111.6,
      },
      {
        first_name: "Brandea",
        last_name: "Balharry",
        gender: "Female",
        temperature: 36.5,
        pulse_rate: 104,
        oxygen_level: 91,
        bp: 130,
        nasal_airflow: 23,
        sc: 3.9,
        A1C: 6.8,
        gl: 97.9,
      },
      {
        first_name: "Georgetta",
        last_name: "Hantusch",
        gender: "Female",
        temperature: 39.2,
        pulse_rate: 94,
        oxygen_level: 98,
        bp: 148,
        nasal_airflow: 37,
        sc: 3.4,
        A1C: 11.4,
        gl: 108.1,
      },
      {
        first_name: "Titus",
        last_name: "Swalough",
        gender: "Male",
        temperature: 38.7,
        pulse_rate: 127,
        oxygen_level: 95,
        bp: 102,
        nasal_airflow: 37,
        sc: 12.7,
        A1C: 4.2,
        gl: 100.6,
      },
      {
        first_name: "Stace",
        last_name: "Carbine",
        gender: "Female",
        temperature: 35.3,
        pulse_rate: 62,
        oxygen_level: 90,
        bp: 128,
        nasal_airflow: 38,
        sc: 8.4,
        A1C: 10.6,
        gl: 93.5,
      },
      {
        first_name: "Andris",
        last_name: "Blumsom",
        gender: "Male",
        temperature: 34.1,
        pulse_rate: 59,
        oxygen_level: 93,
        bp: 125,
        nasal_airflow: 12,
        sc: 12.6,
        A1C: 5.6,
        gl: 101.3,
      },
      {
        first_name: "Dorella",
        last_name: "Noakes",
        gender: "Female",
        temperature: 31.3,
        pulse_rate: 72,
        oxygen_level: 93,
        bp: 99,
        nasal_airflow: 18,
        sc: 12.6,
        A1C: 7.5,
        gl: 81.7,
      },
      {
        first_name: "Julie",
        last_name: "Romke",
        gender: "Male",
        temperature: 34.4,
        pulse_rate: 113,
        oxygen_level: 97,
        bp: 94,
        nasal_airflow: 9,
        sc: 18.4,
        A1C: 3.3,
        gl: 81.1,
      },
      {
        first_name: "Baron",
        last_name: "Daltry",
        gender: "Male",
        temperature: 39.0,
        pulse_rate: 109,
        oxygen_level: 94,
        bp: 138,
        nasal_airflow: 38,
        sc: 3.7,
        A1C: 6.1,
        gl: 62.2,
      },
      {
        first_name: "Karrah",
        last_name: "Henmarsh",
        gender: "Female",
        temperature: 34.9,
        pulse_rate: 117,
        oxygen_level: 100,
        bp: 106,
        nasal_airflow: 15,
        sc: 15.4,
        A1C: 12.3,
        gl: 116.9,
      },
      {
        first_name: "Vivienne",
        last_name: "Dyment",
        gender: "Female",
        temperature: 39.2,
        pulse_rate: 112,
        oxygen_level: 91,
        bp: 97,
        nasal_airflow: 9,
        sc: 5.5,
        A1C: 5.7,
        gl: 49.7,
      },
      {
        first_name: "Marshall",
        last_name: "Stanyforth",
        gender: "Male",
        temperature: 30.7,
        pulse_rate: 107,
        oxygen_level: 98,
        bp: 125,
        nasal_airflow: 19,
        sc: 6.8,
        A1C: 12.8,
        gl: 114.8,
      },
      {
        first_name: "Granny",
        last_name: "Battman",
        gender: "Male",
        temperature: 31.4,
        pulse_rate: 108,
        oxygen_level: 96,
        bp: 129,
        nasal_airflow: 6,
        sc: 18.2,
        A1C: 6.6,
        gl: 122.5,
      },
      {
        first_name: "Koren",
        last_name: "Meus",
        gender: "Female",
        temperature: 38.7,
        pulse_rate: 75,
        oxygen_level: 90,
        bp: 93,
        nasal_airflow: 24,
        sc: 17.1,
        A1C: 14.0,
        gl: 81.7,
      },
      {
        first_name: "Sandye",
        last_name: "Mirams",
        gender: "Female",
        temperature: 30.3,
        pulse_rate: 68,
        oxygen_level: 93,
        bp: 131,
        nasal_airflow: 12,
        sc: 7.0,
        A1C: 3.2,
        gl: 87.7,
      },
      {
        first_name: "Georgianne",
        last_name: "Gonneau",
        gender: "Female",
        temperature: 35.1,
        pulse_rate: 107,
        oxygen_level: 99,
        bp: 144,
        nasal_airflow: 11,
        sc: 13.5,
        A1C: 13.1,
        gl: 128.1,
      },
      {
        first_name: "Madonna",
        last_name: "Murrum",
        gender: "Female",
        temperature: 31.2,
        pulse_rate: 61,
        oxygen_level: 91,
        bp: 111,
        nasal_airflow: 35,
        sc: 4.4,
        A1C: 13.3,
        gl: 64.4,
      },
      {
        first_name: "Morissa",
        last_name: "Nesfield",
        gender: "Female",
        temperature: 36.6,
        pulse_rate: 96,
        oxygen_level: 100,
        bp: 93,
        nasal_airflow: 33,
        sc: 14.8,
        A1C: 7.3,
        gl: 86.5,
      },
      {
        first_name: "Marlee",
        last_name: "Gimson",
        gender: "Female",
        temperature: 37.4,
        pulse_rate: 127,
        oxygen_level: 93,
        bp: 108,
        nasal_airflow: 21,
        sc: 5.4,
        A1C: 11.6,
        gl: 122.4,
      },
      {
        first_name: "Ellette",
        last_name: "Bennit",
        gender: "Female",
        temperature: 38.0,
        pulse_rate: 63,
        oxygen_level: 100,
        bp: 118,
        nasal_airflow: 30,
        sc: 11.1,
        A1C: 14.7,
        gl: 53.6,
      },
      {
        first_name: "Giorgi",
        last_name: "Tuohy",
        gender: "Male",
        temperature: 37.6,
        pulse_rate: 129,
        oxygen_level: 98,
        bp: 107,
        nasal_airflow: 21,
        sc: 18.7,
        A1C: 11.6,
        gl: 85.7,
      },
      {
        first_name: "Marylin",
        last_name: "Harrild",
        gender: "Female",
        temperature: 33.0,
        pulse_rate: 90,
        oxygen_level: 96,
        bp: 102,
        nasal_airflow: 19,
        sc: 1.0,
        A1C: 9.5,
        gl: 59.1,
      },
      {
        first_name: "Marco",
        last_name: "Cozens",
        gender: "Male",
        temperature: 38.3,
        pulse_rate: 100,
        oxygen_level: 98,
        bp: 100,
        nasal_airflow: 20,
        sc: 8.8,
        A1C: 9.4,
        gl: 104.4,
      },
      {
        first_name: "Tedda",
        last_name: "Spivey",
        gender: "Female",
        temperature: 39.3,
        pulse_rate: 58,
        oxygen_level: 100,
        bp: 132,
        nasal_airflow: 32,
        sc: 14.0,
        A1C: 8.6,
        gl: 103.2,
      },
      {
        first_name: "Rene",
        last_name: "Di Bartolommeo",
        gender: "Male",
        temperature: 32.3,
        pulse_rate: 127,
        oxygen_level: 90,
        bp: 140,
        nasal_airflow: 39,
        sc: 15.1,
        A1C: 11.8,
        gl: 72.5,
      },
      {
        first_name: "Ellette",
        last_name: "Canadine",
        gender: "Female",
        temperature: 35.1,
        pulse_rate: 82,
        oxygen_level: 96,
        bp: 141,
        nasal_airflow: 33,
        sc: 17.2,
        A1C: 13.8,
        gl: 81.5,
      },
      {
        first_name: "Katherine",
        last_name: "Fenix",
        gender: "Female",
        temperature: 38.6,
        pulse_rate: 61,
        oxygen_level: 97,
        bp: 128,
        nasal_airflow: 25,
        sc: 13.9,
        A1C: 6.8,
        gl: 73.4,
      },
      {
        first_name: "Rickie",
        last_name: "Wagon",
        gender: "Female",
        temperature: 30.5,
        pulse_rate: 91,
        oxygen_level: 97,
        bp: 135,
        nasal_airflow: 39,
        sc: 18.3,
        A1C: 3.0,
        gl: 72.2,
      },
      {
        first_name: "Tisha",
        last_name: "Rushmer",
        gender: "Female",
        temperature: 34.2,
        pulse_rate: 100,
        oxygen_level: 97,
        bp: 123,
        nasal_airflow: 10,
        sc: 6.5,
        A1C: 6.8,
        gl: 104.6,
      },
      {
        first_name: "Micheal",
        last_name: "Stenners",
        gender: "Male",
        temperature: 31.6,
        pulse_rate: 116,
        oxygen_level: 94,
        bp: 142,
        nasal_airflow: 30,
        sc: 12.1,
        A1C: 10.3,
        gl: 77.5,
      },
      {
        first_name: "Mathian",
        last_name: "Fullman",
        gender: "Male",
        temperature: 33.1,
        pulse_rate: 123,
        oxygen_level: 93,
        bp: 145,
        nasal_airflow: 39,
        sc: 11.5,
        A1C: 7.9,
        gl: 62.8,
      },
      {
        first_name: "Janina",
        last_name: "Claricoats",
        gender: "Female",
        temperature: 32.1,
        pulse_rate: 105,
        oxygen_level: 97,
        bp: 130,
        nasal_airflow: 11,
        sc: 3.3,
        A1C: 3.5,
        gl: 89.5,
      },
      {
        first_name: "Gennifer",
        last_name: "Leggs",
        gender: "Female",
        temperature: 39.1,
        pulse_rate: 93,
        oxygen_level: 98,
        bp: 141,
        nasal_airflow: 32,
        sc: 16.9,
        A1C: 14.3,
        gl: 48.9,
      },
      {
        first_name: "Katinka",
        last_name: "Farriar",
        gender: "Female",
        temperature: 39.7,
        pulse_rate: 91,
        oxygen_level: 99,
        bp: 125,
        nasal_airflow: 18,
        sc: 19.9,
        A1C: 7.9,
        gl: 93.6,
      },
      {
        first_name: "Teresita",
        last_name: "Meharry",
        gender: "Female",
        temperature: 37.6,
        pulse_rate: 111,
        oxygen_level: 94,
        bp: 94,
        nasal_airflow: 24,
        sc: 0.6,
        A1C: 14.9,
        gl: 119.8,
      },
      {
        first_name: "Neala",
        last_name: "Robak",
        gender: "Female",
        temperature: 37.6,
        pulse_rate: 120,
        oxygen_level: 92,
        bp: 150,
        nasal_airflow: 5,
        sc: 14.7,
        A1C: 13.4,
        gl: 52.5,
      },
      {
        first_name: "Sadie",
        last_name: "Delacourt",
        gender: "Female",
        temperature: 35.0,
        pulse_rate: 55,
        oxygen_level: 95,
        bp: 107,
        nasal_airflow: 30,
        sc: 14.4,
        A1C: 13.1,
        gl: 65.4,
      },
      {
        first_name: "Abbi",
        last_name: "Styant",
        gender: "Female",
        temperature: 34.0,
        pulse_rate: 68,
        oxygen_level: 91,
        bp: 140,
        nasal_airflow: 20,
        sc: 1.9,
        A1C: 6.1,
        gl: 83.6,
      },
      {
        first_name: "Olin",
        last_name: "Staig",
        gender: "Male",
        temperature: 36.5,
        pulse_rate: 122,
        oxygen_level: 100,
        bp: 91,
        nasal_airflow: 13,
        sc: 7.0,
        A1C: 11.9,
        gl: 75.6,
      },
      {
        first_name: "Emelyne",
        last_name: "Troucher",
        gender: "Female",
        temperature: 33.1,
        pulse_rate: 90,
        oxygen_level: 95,
        bp: 137,
        nasal_airflow: 36,
        sc: 15.1,
        A1C: 14.5,
        gl: 115.7,
      },
      {
        first_name: "Hazel",
        last_name: "Cruden",
        gender: "Male",
        temperature: 33.7,
        pulse_rate: 106,
        oxygen_level: 95,
        bp: 104,
        nasal_airflow: 35,
        sc: 8.1,
        A1C: 3.9,
        gl: 90.4,
      },
      {
        first_name: "Durant",
        last_name: "Rudkin",
        gender: "Male",
        temperature: 34.9,
        pulse_rate: 121,
        oxygen_level: 93,
        bp: 149,
        nasal_airflow: 14,
        sc: 0.8,
        A1C: 10.1,
        gl: 126.3,
      },
      {
        first_name: "Noemi",
        last_name: "Buff",
        gender: "Female",
        temperature: 32.2,
        pulse_rate: 80,
        oxygen_level: 90,
        bp: 144,
        nasal_airflow: 16,
        sc: 15.9,
        A1C: 14.3,
        gl: 64.8,
      },
      {
        first_name: "Corenda",
        last_name: "Braime",
        gender: "Female",
        temperature: 34.9,
        pulse_rate: 83,
        oxygen_level: 93,
        bp: 138,
        nasal_airflow: 14,
        sc: 1.7,
        A1C: 12.2,
        gl: 74.8,
      },
      {
        first_name: "Franciskus",
        last_name: "Vigours",
        gender: "Male",
        temperature: 38.0,
        pulse_rate: 124,
        oxygen_level: 94,
        bp: 117,
        nasal_airflow: 21,
        sc: 8.5,
        A1C: 4.6,
        gl: 47.0,
      },
      {
        first_name: "Eddy",
        last_name: "Iston",
        gender: "Male",
        temperature: 33.3,
        pulse_rate: 122,
        oxygen_level: 93,
        bp: 110,
        nasal_airflow: 15,
        sc: 7.5,
        A1C: 13.7,
        gl: 68.0,
      },
      {
        first_name: "Mathian",
        last_name: "Ricciardo",
        gender: "Male",
        temperature: 34.7,
        pulse_rate: 127,
        oxygen_level: 99,
        bp: 117,
        nasal_airflow: 5,
        sc: 17.8,
        A1C: 13.3,
        gl: 63.4,
      },
      {
        first_name: "Jeremie",
        last_name: "MacDiarmid",
        gender: "Male",
        temperature: 31.6,
        pulse_rate: 126,
        oxygen_level: 98,
        bp: 138,
        nasal_airflow: 9,
        sc: 0.0,
        A1C: 14.0,
        gl: 62.6,
      },
      {
        first_name: "Ash",
        last_name: "Beaglehole",
        gender: "Male",
        temperature: 31.6,
        pulse_rate: 121,
        oxygen_level: 100,
        bp: 143,
        nasal_airflow: 5,
        sc: 7.5,
        A1C: 3.5,
        gl: 126.6,
      },
      {
        first_name: "Margaretta",
        last_name: "Silly",
        gender: "Female",
        temperature: 39.9,
        pulse_rate: 95,
        oxygen_level: 97,
        bp: 137,
        nasal_airflow: 23,
        sc: 11.0,
        A1C: 9.3,
        gl: 104.6,
      },
      {
        first_name: "Sam",
        last_name: "Mingauld",
        gender: "Female",
        temperature: 39.8,
        pulse_rate: 89,
        oxygen_level: 93,
        bp: 133,
        nasal_airflow: 21,
        sc: 0.6,
        A1C: 4.3,
        gl: 100.3,
      },
      {
        first_name: "Clarke",
        last_name: "Gelling",
        gender: "Male",
        temperature: 39.7,
        pulse_rate: 111,
        oxygen_level: 93,
        bp: 132,
        nasal_airflow: 40,
        sc: 18.1,
        A1C: 7.6,
        gl: 89.2,
      },
      {
        first_name: "Dominique",
        last_name: "Penson",
        gender: "Male",
        temperature: 32.8,
        pulse_rate: 115,
        oxygen_level: 91,
        bp: 114,
        nasal_airflow: 20,
        sc: 6.3,
        A1C: 12.6,
        gl: 79.5,
      },
      {
        first_name: "Sabine",
        last_name: "Wardrop",
        gender: "Female",
        temperature: 31.6,
        pulse_rate: 96,
        oxygen_level: 95,
        bp: 116,
        nasal_airflow: 10,
        sc: 19.3,
        A1C: 7.6,
        gl: 127.7,
      },
      {
        first_name: "Juliette",
        last_name: "Frostdicke",
        gender: "Female",
        temperature: 31.9,
        pulse_rate: 83,
        oxygen_level: 94,
        bp: 106,
        nasal_airflow: 40,
        sc: 10.5,
        A1C: 9.3,
        gl: 113.8,
      },
      {
        first_name: "Carole",
        last_name: "Chinnock",
        gender: "Female",
        temperature: 39.0,
        pulse_rate: 84,
        oxygen_level: 97,
        bp: 99,
        nasal_airflow: 18,
        sc: 13.0,
        A1C: 5.4,
        gl: 114.1,
      },
      {
        first_name: "Calv",
        last_name: "Godber",
        gender: "Male",
        temperature: 39.1,
        pulse_rate: 109,
        oxygen_level: 93,
        bp: 144,
        nasal_airflow: 25,
        sc: 18.6,
        A1C: 14.6,
        gl: 60.4,
      },
      {
        first_name: "Othella",
        last_name: "Swanwick",
        gender: "Female",
        temperature: 35.0,
        pulse_rate: 56,
        oxygen_level: 99,
        bp: 142,
        nasal_airflow: 25,
        sc: 15.8,
        A1C: 13.2,
        gl: 121.1,
      },
      {
        first_name: "Bjorn",
        last_name: "Mocher",
        gender: "Male",
        temperature: 32.1,
        pulse_rate: 95,
        oxygen_level: 98,
        bp: 116,
        nasal_airflow: 36,
        sc: 3.5,
        A1C: 4.2,
        gl: 126.3,
      },
      {
        first_name: "Isidor",
        last_name: "Kerby",
        gender: "Male",
        temperature: 31.7,
        pulse_rate: 107,
        oxygen_level: 95,
        bp: 139,
        nasal_airflow: 8,
        sc: 5.6,
        A1C: 8.4,
        gl: 122.6,
      },
      {
        first_name: "Mikkel",
        last_name: "Marrow",
        gender: "Male",
        temperature: 37.5,
        pulse_rate: 68,
        oxygen_level: 96,
        bp: 120,
        nasal_airflow: 5,
        sc: 10.2,
        A1C: 11.0,
        gl: 70.1,
      },
      {
        first_name: "Lizette",
        last_name: "Kilmurry",
        gender: "Female",
        temperature: 30.5,
        pulse_rate: 62,
        oxygen_level: 98,
        bp: 146,
        nasal_airflow: 35,
        sc: 15.6,
        A1C: 14.1,
        gl: 64.9,
      },
      {
        first_name: "Gerri",
        last_name: "Keenan",
        gender: "Male",
        temperature: 32.9,
        pulse_rate: 122,
        oxygen_level: 98,
        bp: 97,
        nasal_airflow: 11,
        sc: 0.8,
        A1C: 12.5,
        gl: 71.4,
      },
      {
        first_name: "Percival",
        last_name: "Sander",
        gender: "Male",
        temperature: 38.0,
        pulse_rate: 59,
        oxygen_level: 92,
        bp: 90,
        nasal_airflow: 7,
        sc: 18.0,
        A1C: 10.3,
        gl: 68.5,
      },
      {
        first_name: "Irwinn",
        last_name: "Calbaithe",
        gender: "Male",
        temperature: 34.3,
        pulse_rate: 83,
        oxygen_level: 99,
        bp: 114,
        nasal_airflow: 16,
        sc: 12.1,
        A1C: 12.2,
        gl: 110.2,
      },
      {
        first_name: "Roanna",
        last_name: "Boissier",
        gender: "Female",
        temperature: 30.5,
        pulse_rate: 96,
        oxygen_level: 98,
        bp: 129,
        nasal_airflow: 10,
        sc: 8.1,
        A1C: 8.1,
        gl: 111.4,
      },
      {
        first_name: "Drew",
        last_name: "Standish",
        gender: "Male",
        temperature: 30.1,
        pulse_rate: 91,
        oxygen_level: 97,
        bp: 115,
        nasal_airflow: 21,
        sc: 8.2,
        A1C: 12.7,
        gl: 82.2,
      },
      {
        first_name: "Kalindi",
        last_name: "Cristofvao",
        gender: "Female",
        temperature: 37.0,
        pulse_rate: 86,
        oxygen_level: 98,
        bp: 122,
        nasal_airflow: 25,
        sc: 17.4,
        A1C: 13.8,
        gl: 54.9,
      },
      {
        first_name: "Bancroft",
        last_name: "Brower",
        gender: "Male",
        temperature: 34.3,
        pulse_rate: 89,
        oxygen_level: 97,
        bp: 142,
        nasal_airflow: 8,
        sc: 19.0,
        A1C: 14.9,
        gl: 83.9,
      },
      {
        first_name: "Marcile",
        last_name: "Suggitt",
        gender: "Female",
        temperature: 38.6,
        pulse_rate: 99,
        oxygen_level: 92,
        bp: 108,
        nasal_airflow: 28,
        sc: 8.3,
        A1C: 11.8,
        gl: 73.5,
      },
      {
        first_name: "Alford",
        last_name: "Harg",
        gender: "Male",
        temperature: 39.2,
        pulse_rate: 112,
        oxygen_level: 98,
        bp: 102,
        nasal_airflow: 10,
        sc: 0.9,
        A1C: 9.3,
        gl: 45.4,
      },
      {
        first_name: "Jelene",
        last_name: "Poschel",
        gender: "Female",
        temperature: 32.6,
        pulse_rate: 85,
        oxygen_level: 94,
        bp: 132,
        nasal_airflow: 15,
        sc: 14.7,
        A1C: 14.2,
        gl: 124.6,
      },
      {
        first_name: "Corbin",
        last_name: "Arger",
        gender: "Male",
        temperature: 30.6,
        pulse_rate: 110,
        oxygen_level: 99,
        bp: 134,
        nasal_airflow: 25,
        sc: 17.3,
        A1C: 6.6,
        gl: 80.7,
      },
      {
        first_name: "Jedediah",
        last_name: "Measor",
        gender: "Male",
        temperature: 36.8,
        pulse_rate: 123,
        oxygen_level: 91,
        bp: 92,
        nasal_airflow: 7,
        sc: 9.7,
        A1C: 11.8,
        gl: 58.6,
      },
      {
        first_name: "Lyda",
        last_name: "Shier",
        gender: "Female",
        temperature: 33.5,
        pulse_rate: 130,
        oxygen_level: 98,
        bp: 113,
        nasal_airflow: 9,
        sc: 13.8,
        A1C: 13.1,
        gl: 106.8,
      },
      {
        first_name: "Giulio",
        last_name: "Twelftree",
        gender: "Male",
        temperature: 33.5,
        pulse_rate: 58,
        oxygen_level: 97,
        bp: 126,
        nasal_airflow: 16,
        sc: 14.1,
        A1C: 4.9,
        gl: 95.9,
      },
    ],
  };
  // (Note that because `price` and such are given as strings in your object,
  // the below relies on the fact that <= and >= with a string and number
  // will coerce the string to a number before comparing.)
  var name = window.localStorage.getItem("drMedName");
  if (name.includes("Doctor") || name.includes("doctor")) {
    var image1 = document.getElementById("graph1");
    image1.src = "graph1.jpeg";
    var image2 = document.getElementById("graph1");
    image2.src = "graph2.jpeg";

    let dataStr = JSON.stringify(obj);
    let dataUri =
      "data:application/json;charset=utf-8," + encodeURIComponent(dataStr);

    let exportFileDefaultName = "data.json";

    let linkElement = document.createElement("a");
    linkElement.setAttribute("href", dataUri);
    linkElement.setAttribute("download", exportFileDefaultName);
    linkElement.click();
    console.log("Downloaded!");
  } else {
    var newArray = obj.patient.filter(function (el) {
      return el.first_name == name; // Changed this so a home would match
    });
    console.log(newArray);
    var mainContainer = document.getElementById("dataInfo");

    for (var i = 0; i < newArray.length; i++) {
      var div = document.createElement("div");
      div.innerHTML =
        "Name: " +
        newArray[i].first_name +
        "<br />" +
        "Gender: " +
        newArray[i].gender +
        "<br />" +
        "Temperature: " +
        newArray[i].temperature +
        "C" +
        "<br />" +
        "Pulse Rate: " +
        newArray[i].pulse_rate +
        " BPM" +
        "<br />" +
        "Oxygen Level: " +
        newArray[i].oxygen_level +
        "<br />" +
        " Blood Pressure: " +
        newArray[i].bp +
        "<br />" +
        " Nasal Airflow: " +
        newArray[i].nasal_airflow +
        "<br />" +
        " A1C Level: " +
        newArray[i].A1C +
        " mg/dL" +
        "<br />" +
        "Skin Conductance: " +
        newArray[i].sc +
        "uS" +
        "<br />" +
        "Glucose Level: " +
        newArray[i].gl;
      mainContainer.appendChild(div);
    }
  }
}
